---
- name: Install git via Homebrew
  package:
    name: git
    state: latest
  when: ansible_os_family == "Darwin"

- name: Add global user.name to git
  command: git config --global user.name "{{ git_user_name }}"
  when: ansible_os_family == "Darwin" and git_user_name != ""

- name: Add global user.email to git
  command: git config --global user.email "{{ git_user_email }}"
  when: ansible_os_family == "Darwin" and git_user_email != ""

- name: Add global core.editor to git
  command: git config --global core.editor "{{ git_editor }}"
  when: ansible_os_family == "Darwin" and git_editor != ""
